/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const TOKEN_KEY: typeof import('./src/utils/cookie1')['TOKEN_KEY']
  const createRef: typeof import('react')['createRef']
  const delToken: typeof import('./src/utils/cookie1')['delToken']
  const forwardRef: typeof import('react')['forwardRef']
  const getToken: typeof import('./src/utils/cookie1')['getToken']
  const lazy: typeof import('react')['lazy']
  const loadToken: typeof import('./src/utils/cookie')['loadToken']
  const memo: typeof import('react')['memo']
  const request: typeof import('./src/utils/request')['request']
  const saveToken: typeof import('./src/utils/cookie')['saveToken']
  const setToken: typeof import('./src/utils/cookie1')['setToken']
  const startTransition: typeof import('react')['startTransition']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
